/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisualRouteImport } from './routes/visual'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWrappedRouteImport } from './routes/app.wrapped'
import { Route as AppTimelineRouteImport } from './routes/app.timeline'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSearchRouteImport } from './routes/app.search'
import { Route as AppSaveForLaterRouteImport } from './routes/app.save-for-later'
import { Route as AppQuotesRouteImport } from './routes/app.quotes'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMuseumRouteImport } from './routes/app.museum'
import { Route as AppLibraryRouteImport } from './routes/app.library'
import { Route as AppJournalRouteImport } from './routes/app.journal'
import { Route as AppImportRouteImport } from './routes/app.import'
import { Route as AppGoalsRouteImport } from './routes/app.goals'
import { Route as AppDevRouteImport } from './routes/app.dev'
import { Route as AppCollectionsRouteImport } from './routes/app.collections'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppBookmarksRouteImport } from './routes/app.bookmarks'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAchievementsRouteImport } from './routes/app.achievements'
import { Route as AppLibraryIndexRouteImport } from './routes/app.library.index'
import { Route as AppFranchisesIndexRouteImport } from './routes/app.franchises.index'
import { Route as AppCreatorsIndexRouteImport } from './routes/app.creators.index'
import { Route as AppCollectionsIndexRouteImport } from './routes/app.collections.index'
import { Route as AppCharactersIndexRouteImport } from './routes/app.characters.index'
import { Route as AppTagsTagRouteImport } from './routes/app.tags.$tag'
import { Route as AppMediaIdRouteImport } from './routes/app.media.$id'
import { Route as AppLibraryRewatchingRouteImport } from './routes/app.library.rewatching'
import { Route as AppLibraryRecentlyFinishedRouteImport } from './routes/app.library.recently-finished'
import { Route as AppLibraryPlanningRouteImport } from './routes/app.library.planning'
import { Route as AppLibraryPausedRouteImport } from './routes/app.library.paused'
import { Route as AppLibraryInProgressRouteImport } from './routes/app.library.in-progress'
import { Route as AppLibraryFavoritesRouteImport } from './routes/app.library.favorites'
import { Route as AppLibraryDroppedRouteImport } from './routes/app.library.dropped'
import { Route as AppLibraryContinueRouteImport } from './routes/app.library.continue'
import { Route as AppLibraryCompletedRouteImport } from './routes/app.library.completed'
import { Route as AppLibraryArchivedRouteImport } from './routes/app.library.archived'
import { Route as AppLibraryAllRouteImport } from './routes/app.library.all'
import { Route as AppLibraryKindRouteImport } from './routes/app.library.$kind'
import { Route as AppFranchisesIdRouteImport } from './routes/app.franchises.$id'
import { Route as AppCreatorsIdRouteImport } from './routes/app.creators.$id'
import { Route as AppCollectionsIdRouteImport } from './routes/app.collections.$id'
import { Route as AppCharactersIdRouteImport } from './routes/app.characters.$id'

const VisualRoute = VisualRouteImport.update({
  id: '/visual',
  path: '/visual',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWrappedRoute = AppWrappedRouteImport.update({
  id: '/wrapped',
  path: '/wrapped',
  getParentRoute: () => AppRoute,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSaveForLaterRoute = AppSaveForLaterRouteImport.update({
  id: '/save-for-later',
  path: '/save-for-later',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotesRoute = AppQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMuseumRoute = AppMuseumRouteImport.update({
  id: '/museum',
  path: '/museum',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppDevRoute = AppDevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsRoute = AppCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppBookmarksRoute = AppBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryIndexRoute = AppLibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLibraryRoute,
} as any)
const AppFranchisesIndexRoute = AppFranchisesIndexRouteImport.update({
  id: '/franchises/',
  path: '/franchises/',
  getParentRoute: () => AppRoute,
} as any)
const AppCreatorsIndexRoute = AppCreatorsIndexRouteImport.update({
  id: '/creators/',
  path: '/creators/',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsIndexRoute = AppCollectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCollectionsRoute,
} as any)
const AppCharactersIndexRoute = AppCharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => AppRoute,
} as any)
const AppTagsTagRoute = AppTagsTagRouteImport.update({
  id: '/tags/$tag',
  path: '/tags/$tag',
  getParentRoute: () => AppRoute,
} as any)
const AppMediaIdRoute = AppMediaIdRouteImport.update({
  id: '/media/$id',
  path: '/media/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRewatchingRoute = AppLibraryRewatchingRouteImport.update({
  id: '/rewatching',
  path: '/rewatching',
  getParentRoute: () => AppLibraryRoute,
} as any)
const AppLibraryRecentlyFinishedRoute =
  AppLibraryRecentlyFinishedRouteImport.update({
    id: '/recently-finished',
    path: '/recently-finished',
    getParentRoute: () => AppLibraryRoute,
  } as any)
const AppLibraryPlanningRoute = AppLibraryPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => AppLibraryRoute,
} as any)
const AppLibraryPausedRoute = AppLibraryPausedRouteImport.update({
  id: '/paused',
  path: '/paused',
  getParentRoute: () => AppLibraryRoute,
} as any)
const AppLibraryInProgressRoute = AppLibraryInProgressRouteImport.update({
  id: '/in-progress',
  path: '/in-progress',
  getParentRoute: () => AppLibraryRoute,
} as any)
const AppLibraryFavoritesRoute = AppLibraryFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppLibraryRoute,
} as any)
const AppLibraryDroppedRoute = AppLibraryDroppedRouteImport.update({
  id: '/dropped',
  path: '/dropped',
  getParentRoute: () => AppLibraryRoute,
} as any)
const AppLibraryContinueRoute = AppLibraryContinueRouteImport.update({
  id: '/continue',
  path: '/continue',
  getParentRoute: () => AppLibraryRoute,
} as any)
const AppLibraryCompletedRoute = AppLibraryCompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => AppLibraryRoute,
} as any)
const AppLibraryArchivedRoute = AppLibraryArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => AppLibraryRoute,
} as any)
const AppLibraryAllRoute = AppLibraryAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => AppLibraryRoute,
} as any)
const AppLibraryKindRoute = AppLibraryKindRouteImport.update({
  id: '/$kind',
  path: '/$kind',
  getParentRoute: () => AppLibraryRoute,
} as any)
const AppFranchisesIdRoute = AppFranchisesIdRouteImport.update({
  id: '/franchises/$id',
  path: '/franchises/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCreatorsIdRoute = AppCreatorsIdRouteImport.update({
  id: '/creators/$id',
  path: '/creators/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsIdRoute = AppCollectionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCollectionsRoute,
} as any)
const AppCharactersIdRoute = AppCharactersIdRouteImport.update({
  id: '/characters/$id',
  path: '/characters/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/visual': typeof VisualRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/bookmarks': typeof AppBookmarksRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/collections': typeof AppCollectionsRouteWithChildren
  '/app/dev': typeof AppDevRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/import': typeof AppImportRoute
  '/app/journal': typeof AppJournalRoute
  '/app/library': typeof AppLibraryRouteWithChildren
  '/app/museum': typeof AppMuseumRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/profile': typeof AppProfileRoute
  '/app/quotes': typeof AppQuotesRoute
  '/app/save-for-later': typeof AppSaveForLaterRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/timeline': typeof AppTimelineRoute
  '/app/wrapped': typeof AppWrappedRoute
  '/app/': typeof AppIndexRoute
  '/app/characters/$id': typeof AppCharactersIdRoute
  '/app/collections/$id': typeof AppCollectionsIdRoute
  '/app/creators/$id': typeof AppCreatorsIdRoute
  '/app/franchises/$id': typeof AppFranchisesIdRoute
  '/app/library/$kind': typeof AppLibraryKindRoute
  '/app/library/all': typeof AppLibraryAllRoute
  '/app/library/archived': typeof AppLibraryArchivedRoute
  '/app/library/completed': typeof AppLibraryCompletedRoute
  '/app/library/continue': typeof AppLibraryContinueRoute
  '/app/library/dropped': typeof AppLibraryDroppedRoute
  '/app/library/favorites': typeof AppLibraryFavoritesRoute
  '/app/library/in-progress': typeof AppLibraryInProgressRoute
  '/app/library/paused': typeof AppLibraryPausedRoute
  '/app/library/planning': typeof AppLibraryPlanningRoute
  '/app/library/recently-finished': typeof AppLibraryRecentlyFinishedRoute
  '/app/library/rewatching': typeof AppLibraryRewatchingRoute
  '/app/media/$id': typeof AppMediaIdRoute
  '/app/tags/$tag': typeof AppTagsTagRoute
  '/app/characters/': typeof AppCharactersIndexRoute
  '/app/collections/': typeof AppCollectionsIndexRoute
  '/app/creators/': typeof AppCreatorsIndexRoute
  '/app/franchises/': typeof AppFranchisesIndexRoute
  '/app/library/': typeof AppLibraryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/visual': typeof VisualRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/bookmarks': typeof AppBookmarksRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dev': typeof AppDevRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/import': typeof AppImportRoute
  '/app/journal': typeof AppJournalRoute
  '/app/museum': typeof AppMuseumRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/profile': typeof AppProfileRoute
  '/app/quotes': typeof AppQuotesRoute
  '/app/save-for-later': typeof AppSaveForLaterRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/timeline': typeof AppTimelineRoute
  '/app/wrapped': typeof AppWrappedRoute
  '/app': typeof AppIndexRoute
  '/app/characters/$id': typeof AppCharactersIdRoute
  '/app/collections/$id': typeof AppCollectionsIdRoute
  '/app/creators/$id': typeof AppCreatorsIdRoute
  '/app/franchises/$id': typeof AppFranchisesIdRoute
  '/app/library/$kind': typeof AppLibraryKindRoute
  '/app/library/all': typeof AppLibraryAllRoute
  '/app/library/archived': typeof AppLibraryArchivedRoute
  '/app/library/completed': typeof AppLibraryCompletedRoute
  '/app/library/continue': typeof AppLibraryContinueRoute
  '/app/library/dropped': typeof AppLibraryDroppedRoute
  '/app/library/favorites': typeof AppLibraryFavoritesRoute
  '/app/library/in-progress': typeof AppLibraryInProgressRoute
  '/app/library/paused': typeof AppLibraryPausedRoute
  '/app/library/planning': typeof AppLibraryPlanningRoute
  '/app/library/recently-finished': typeof AppLibraryRecentlyFinishedRoute
  '/app/library/rewatching': typeof AppLibraryRewatchingRoute
  '/app/media/$id': typeof AppMediaIdRoute
  '/app/tags/$tag': typeof AppTagsTagRoute
  '/app/characters': typeof AppCharactersIndexRoute
  '/app/collections': typeof AppCollectionsIndexRoute
  '/app/creators': typeof AppCreatorsIndexRoute
  '/app/franchises': typeof AppFranchisesIndexRoute
  '/app/library': typeof AppLibraryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/visual': typeof VisualRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/bookmarks': typeof AppBookmarksRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/collections': typeof AppCollectionsRouteWithChildren
  '/app/dev': typeof AppDevRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/import': typeof AppImportRoute
  '/app/journal': typeof AppJournalRoute
  '/app/library': typeof AppLibraryRouteWithChildren
  '/app/museum': typeof AppMuseumRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/profile': typeof AppProfileRoute
  '/app/quotes': typeof AppQuotesRoute
  '/app/save-for-later': typeof AppSaveForLaterRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/timeline': typeof AppTimelineRoute
  '/app/wrapped': typeof AppWrappedRoute
  '/app/': typeof AppIndexRoute
  '/app/characters/$id': typeof AppCharactersIdRoute
  '/app/collections/$id': typeof AppCollectionsIdRoute
  '/app/creators/$id': typeof AppCreatorsIdRoute
  '/app/franchises/$id': typeof AppFranchisesIdRoute
  '/app/library/$kind': typeof AppLibraryKindRoute
  '/app/library/all': typeof AppLibraryAllRoute
  '/app/library/archived': typeof AppLibraryArchivedRoute
  '/app/library/completed': typeof AppLibraryCompletedRoute
  '/app/library/continue': typeof AppLibraryContinueRoute
  '/app/library/dropped': typeof AppLibraryDroppedRoute
  '/app/library/favorites': typeof AppLibraryFavoritesRoute
  '/app/library/in-progress': typeof AppLibraryInProgressRoute
  '/app/library/paused': typeof AppLibraryPausedRoute
  '/app/library/planning': typeof AppLibraryPlanningRoute
  '/app/library/recently-finished': typeof AppLibraryRecentlyFinishedRoute
  '/app/library/rewatching': typeof AppLibraryRewatchingRoute
  '/app/media/$id': typeof AppMediaIdRoute
  '/app/tags/$tag': typeof AppTagsTagRoute
  '/app/characters/': typeof AppCharactersIndexRoute
  '/app/collections/': typeof AppCollectionsIndexRoute
  '/app/creators/': typeof AppCreatorsIndexRoute
  '/app/franchises/': typeof AppFranchisesIndexRoute
  '/app/library/': typeof AppLibraryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/pricing'
    | '/visual'
    | '/app/achievements'
    | '/app/analytics'
    | '/app/bookmarks'
    | '/app/calendar'
    | '/app/collections'
    | '/app/dev'
    | '/app/goals'
    | '/app/import'
    | '/app/journal'
    | '/app/library'
    | '/app/museum'
    | '/app/notifications'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/quotes'
    | '/app/save-for-later'
    | '/app/search'
    | '/app/settings'
    | '/app/timeline'
    | '/app/wrapped'
    | '/app/'
    | '/app/characters/$id'
    | '/app/collections/$id'
    | '/app/creators/$id'
    | '/app/franchises/$id'
    | '/app/library/$kind'
    | '/app/library/all'
    | '/app/library/archived'
    | '/app/library/completed'
    | '/app/library/continue'
    | '/app/library/dropped'
    | '/app/library/favorites'
    | '/app/library/in-progress'
    | '/app/library/paused'
    | '/app/library/planning'
    | '/app/library/recently-finished'
    | '/app/library/rewatching'
    | '/app/media/$id'
    | '/app/tags/$tag'
    | '/app/characters/'
    | '/app/collections/'
    | '/app/creators/'
    | '/app/franchises/'
    | '/app/library/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pricing'
    | '/visual'
    | '/app/achievements'
    | '/app/analytics'
    | '/app/bookmarks'
    | '/app/calendar'
    | '/app/dev'
    | '/app/goals'
    | '/app/import'
    | '/app/journal'
    | '/app/museum'
    | '/app/notifications'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/quotes'
    | '/app/save-for-later'
    | '/app/search'
    | '/app/settings'
    | '/app/timeline'
    | '/app/wrapped'
    | '/app'
    | '/app/characters/$id'
    | '/app/collections/$id'
    | '/app/creators/$id'
    | '/app/franchises/$id'
    | '/app/library/$kind'
    | '/app/library/all'
    | '/app/library/archived'
    | '/app/library/completed'
    | '/app/library/continue'
    | '/app/library/dropped'
    | '/app/library/favorites'
    | '/app/library/in-progress'
    | '/app/library/paused'
    | '/app/library/planning'
    | '/app/library/recently-finished'
    | '/app/library/rewatching'
    | '/app/media/$id'
    | '/app/tags/$tag'
    | '/app/characters'
    | '/app/collections'
    | '/app/creators'
    | '/app/franchises'
    | '/app/library'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/pricing'
    | '/visual'
    | '/app/achievements'
    | '/app/analytics'
    | '/app/bookmarks'
    | '/app/calendar'
    | '/app/collections'
    | '/app/dev'
    | '/app/goals'
    | '/app/import'
    | '/app/journal'
    | '/app/library'
    | '/app/museum'
    | '/app/notifications'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/quotes'
    | '/app/save-for-later'
    | '/app/search'
    | '/app/settings'
    | '/app/timeline'
    | '/app/wrapped'
    | '/app/'
    | '/app/characters/$id'
    | '/app/collections/$id'
    | '/app/creators/$id'
    | '/app/franchises/$id'
    | '/app/library/$kind'
    | '/app/library/all'
    | '/app/library/archived'
    | '/app/library/completed'
    | '/app/library/continue'
    | '/app/library/dropped'
    | '/app/library/favorites'
    | '/app/library/in-progress'
    | '/app/library/paused'
    | '/app/library/planning'
    | '/app/library/recently-finished'
    | '/app/library/rewatching'
    | '/app/media/$id'
    | '/app/tags/$tag'
    | '/app/characters/'
    | '/app/collections/'
    | '/app/creators/'
    | '/app/franchises/'
    | '/app/library/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  PricingRoute: typeof PricingRoute
  VisualRoute: typeof VisualRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visual': {
      id: '/visual'
      path: '/visual'
      fullPath: '/visual'
      preLoaderRoute: typeof VisualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wrapped': {
      id: '/app/wrapped'
      path: '/wrapped'
      fullPath: '/app/wrapped'
      preLoaderRoute: typeof AppWrappedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/timeline': {
      id: '/app/timeline'
      path: '/timeline'
      fullPath: '/app/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/save-for-later': {
      id: '/app/save-for-later'
      path: '/save-for-later'
      fullPath: '/app/save-for-later'
      preLoaderRoute: typeof AppSaveForLaterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quotes': {
      id: '/app/quotes'
      path: '/quotes'
      fullPath: '/app/quotes'
      preLoaderRoute: typeof AppQuotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/museum': {
      id: '/app/museum'
      path: '/museum'
      fullPath: '/app/museum'
      preLoaderRoute: typeof AppMuseumRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library': {
      id: '/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/journal': {
      id: '/app/journal'
      path: '/journal'
      fullPath: '/app/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/import': {
      id: '/app/import'
      path: '/import'
      fullPath: '/app/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/goals': {
      id: '/app/goals'
      path: '/goals'
      fullPath: '/app/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dev': {
      id: '/app/dev'
      path: '/dev'
      fullPath: '/app/dev'
      preLoaderRoute: typeof AppDevRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/collections': {
      id: '/app/collections'
      path: '/collections'
      fullPath: '/app/collections'
      preLoaderRoute: typeof AppCollectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookmarks': {
      id: '/app/bookmarks'
      path: '/bookmarks'
      fullPath: '/app/bookmarks'
      preLoaderRoute: typeof AppBookmarksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/achievements': {
      id: '/app/achievements'
      path: '/achievements'
      fullPath: '/app/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library/': {
      id: '/app/library/'
      path: '/'
      fullPath: '/app/library/'
      preLoaderRoute: typeof AppLibraryIndexRouteImport
      parentRoute: typeof AppLibraryRoute
    }
    '/app/franchises/': {
      id: '/app/franchises/'
      path: '/franchises'
      fullPath: '/app/franchises/'
      preLoaderRoute: typeof AppFranchisesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/creators/': {
      id: '/app/creators/'
      path: '/creators'
      fullPath: '/app/creators/'
      preLoaderRoute: typeof AppCreatorsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/collections/': {
      id: '/app/collections/'
      path: '/'
      fullPath: '/app/collections/'
      preLoaderRoute: typeof AppCollectionsIndexRouteImport
      parentRoute: typeof AppCollectionsRoute
    }
    '/app/characters/': {
      id: '/app/characters/'
      path: '/characters'
      fullPath: '/app/characters/'
      preLoaderRoute: typeof AppCharactersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tags/$tag': {
      id: '/app/tags/$tag'
      path: '/tags/$tag'
      fullPath: '/app/tags/$tag'
      preLoaderRoute: typeof AppTagsTagRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/media/$id': {
      id: '/app/media/$id'
      path: '/media/$id'
      fullPath: '/app/media/$id'
      preLoaderRoute: typeof AppMediaIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library/rewatching': {
      id: '/app/library/rewatching'
      path: '/rewatching'
      fullPath: '/app/library/rewatching'
      preLoaderRoute: typeof AppLibraryRewatchingRouteImport
      parentRoute: typeof AppLibraryRoute
    }
    '/app/library/recently-finished': {
      id: '/app/library/recently-finished'
      path: '/recently-finished'
      fullPath: '/app/library/recently-finished'
      preLoaderRoute: typeof AppLibraryRecentlyFinishedRouteImport
      parentRoute: typeof AppLibraryRoute
    }
    '/app/library/planning': {
      id: '/app/library/planning'
      path: '/planning'
      fullPath: '/app/library/planning'
      preLoaderRoute: typeof AppLibraryPlanningRouteImport
      parentRoute: typeof AppLibraryRoute
    }
    '/app/library/paused': {
      id: '/app/library/paused'
      path: '/paused'
      fullPath: '/app/library/paused'
      preLoaderRoute: typeof AppLibraryPausedRouteImport
      parentRoute: typeof AppLibraryRoute
    }
    '/app/library/in-progress': {
      id: '/app/library/in-progress'
      path: '/in-progress'
      fullPath: '/app/library/in-progress'
      preLoaderRoute: typeof AppLibraryInProgressRouteImport
      parentRoute: typeof AppLibraryRoute
    }
    '/app/library/favorites': {
      id: '/app/library/favorites'
      path: '/favorites'
      fullPath: '/app/library/favorites'
      preLoaderRoute: typeof AppLibraryFavoritesRouteImport
      parentRoute: typeof AppLibraryRoute
    }
    '/app/library/dropped': {
      id: '/app/library/dropped'
      path: '/dropped'
      fullPath: '/app/library/dropped'
      preLoaderRoute: typeof AppLibraryDroppedRouteImport
      parentRoute: typeof AppLibraryRoute
    }
    '/app/library/continue': {
      id: '/app/library/continue'
      path: '/continue'
      fullPath: '/app/library/continue'
      preLoaderRoute: typeof AppLibraryContinueRouteImport
      parentRoute: typeof AppLibraryRoute
    }
    '/app/library/completed': {
      id: '/app/library/completed'
      path: '/completed'
      fullPath: '/app/library/completed'
      preLoaderRoute: typeof AppLibraryCompletedRouteImport
      parentRoute: typeof AppLibraryRoute
    }
    '/app/library/archived': {
      id: '/app/library/archived'
      path: '/archived'
      fullPath: '/app/library/archived'
      preLoaderRoute: typeof AppLibraryArchivedRouteImport
      parentRoute: typeof AppLibraryRoute
    }
    '/app/library/all': {
      id: '/app/library/all'
      path: '/all'
      fullPath: '/app/library/all'
      preLoaderRoute: typeof AppLibraryAllRouteImport
      parentRoute: typeof AppLibraryRoute
    }
    '/app/library/$kind': {
      id: '/app/library/$kind'
      path: '/$kind'
      fullPath: '/app/library/$kind'
      preLoaderRoute: typeof AppLibraryKindRouteImport
      parentRoute: typeof AppLibraryRoute
    }
    '/app/franchises/$id': {
      id: '/app/franchises/$id'
      path: '/franchises/$id'
      fullPath: '/app/franchises/$id'
      preLoaderRoute: typeof AppFranchisesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/creators/$id': {
      id: '/app/creators/$id'
      path: '/creators/$id'
      fullPath: '/app/creators/$id'
      preLoaderRoute: typeof AppCreatorsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/collections/$id': {
      id: '/app/collections/$id'
      path: '/$id'
      fullPath: '/app/collections/$id'
      preLoaderRoute: typeof AppCollectionsIdRouteImport
      parentRoute: typeof AppCollectionsRoute
    }
    '/app/characters/$id': {
      id: '/app/characters/$id'
      path: '/characters/$id'
      fullPath: '/app/characters/$id'
      preLoaderRoute: typeof AppCharactersIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppCollectionsRouteChildren {
  AppCollectionsIdRoute: typeof AppCollectionsIdRoute
  AppCollectionsIndexRoute: typeof AppCollectionsIndexRoute
}

const AppCollectionsRouteChildren: AppCollectionsRouteChildren = {
  AppCollectionsIdRoute: AppCollectionsIdRoute,
  AppCollectionsIndexRoute: AppCollectionsIndexRoute,
}

const AppCollectionsRouteWithChildren = AppCollectionsRoute._addFileChildren(
  AppCollectionsRouteChildren,
)

interface AppLibraryRouteChildren {
  AppLibraryKindRoute: typeof AppLibraryKindRoute
  AppLibraryAllRoute: typeof AppLibraryAllRoute
  AppLibraryArchivedRoute: typeof AppLibraryArchivedRoute
  AppLibraryCompletedRoute: typeof AppLibraryCompletedRoute
  AppLibraryContinueRoute: typeof AppLibraryContinueRoute
  AppLibraryDroppedRoute: typeof AppLibraryDroppedRoute
  AppLibraryFavoritesRoute: typeof AppLibraryFavoritesRoute
  AppLibraryInProgressRoute: typeof AppLibraryInProgressRoute
  AppLibraryPausedRoute: typeof AppLibraryPausedRoute
  AppLibraryPlanningRoute: typeof AppLibraryPlanningRoute
  AppLibraryRecentlyFinishedRoute: typeof AppLibraryRecentlyFinishedRoute
  AppLibraryRewatchingRoute: typeof AppLibraryRewatchingRoute
  AppLibraryIndexRoute: typeof AppLibraryIndexRoute
}

const AppLibraryRouteChildren: AppLibraryRouteChildren = {
  AppLibraryKindRoute: AppLibraryKindRoute,
  AppLibraryAllRoute: AppLibraryAllRoute,
  AppLibraryArchivedRoute: AppLibraryArchivedRoute,
  AppLibraryCompletedRoute: AppLibraryCompletedRoute,
  AppLibraryContinueRoute: AppLibraryContinueRoute,
  AppLibraryDroppedRoute: AppLibraryDroppedRoute,
  AppLibraryFavoritesRoute: AppLibraryFavoritesRoute,
  AppLibraryInProgressRoute: AppLibraryInProgressRoute,
  AppLibraryPausedRoute: AppLibraryPausedRoute,
  AppLibraryPlanningRoute: AppLibraryPlanningRoute,
  AppLibraryRecentlyFinishedRoute: AppLibraryRecentlyFinishedRoute,
  AppLibraryRewatchingRoute: AppLibraryRewatchingRoute,
  AppLibraryIndexRoute: AppLibraryIndexRoute,
}

const AppLibraryRouteWithChildren = AppLibraryRoute._addFileChildren(
  AppLibraryRouteChildren,
)

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBookmarksRoute: typeof AppBookmarksRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCollectionsRoute: typeof AppCollectionsRouteWithChildren
  AppDevRoute: typeof AppDevRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppImportRoute: typeof AppImportRoute
  AppJournalRoute: typeof AppJournalRoute
  AppLibraryRoute: typeof AppLibraryRouteWithChildren
  AppMuseumRoute: typeof AppMuseumRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppProfileRoute: typeof AppProfileRoute
  AppQuotesRoute: typeof AppQuotesRoute
  AppSaveForLaterRoute: typeof AppSaveForLaterRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTimelineRoute: typeof AppTimelineRoute
  AppWrappedRoute: typeof AppWrappedRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCharactersIdRoute: typeof AppCharactersIdRoute
  AppCreatorsIdRoute: typeof AppCreatorsIdRoute
  AppFranchisesIdRoute: typeof AppFranchisesIdRoute
  AppMediaIdRoute: typeof AppMediaIdRoute
  AppTagsTagRoute: typeof AppTagsTagRoute
  AppCharactersIndexRoute: typeof AppCharactersIndexRoute
  AppCreatorsIndexRoute: typeof AppCreatorsIndexRoute
  AppFranchisesIndexRoute: typeof AppFranchisesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBookmarksRoute: AppBookmarksRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCollectionsRoute: AppCollectionsRouteWithChildren,
  AppDevRoute: AppDevRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppImportRoute: AppImportRoute,
  AppJournalRoute: AppJournalRoute,
  AppLibraryRoute: AppLibraryRouteWithChildren,
  AppMuseumRoute: AppMuseumRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppProfileRoute: AppProfileRoute,
  AppQuotesRoute: AppQuotesRoute,
  AppSaveForLaterRoute: AppSaveForLaterRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTimelineRoute: AppTimelineRoute,
  AppWrappedRoute: AppWrappedRoute,
  AppIndexRoute: AppIndexRoute,
  AppCharactersIdRoute: AppCharactersIdRoute,
  AppCreatorsIdRoute: AppCreatorsIdRoute,
  AppFranchisesIdRoute: AppFranchisesIdRoute,
  AppMediaIdRoute: AppMediaIdRoute,
  AppTagsTagRoute: AppTagsTagRoute,
  AppCharactersIndexRoute: AppCharactersIndexRoute,
  AppCreatorsIndexRoute: AppCreatorsIndexRoute,
  AppFranchisesIndexRoute: AppFranchisesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  PricingRoute: PricingRoute,
  VisualRoute: VisualRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
